serde-rs/serde-rs.github.io

src/README.md
We built a serde adapter for deserializing the redis::Value type and
have been using it in production for several months. It only has a few
stars/crates.io downloads, so people either don't know about it or don't
need it. Adding it here would address the former case.
=> Add Redis to list of supported formats

src/attributes.md
Using a function with the old signature on Serde 0.9 results in a very confusing error message:
```
error[E0308]: mismatched types
--> codegen/src/botocore.rs:5:17
|
5 | #[derive(Debug, Deserialize)]
|                 ^^^^^^^^^^^ expected &mut _, found type parameter
|
= note: expected type `&mut _`
= note:    found type `__D`
```
Since you don't see the generated code, this would be likely to trip up people less familiar with serde.
=> Update required signatures of serialize_with and deserialize_with attributes for serde 0.9

src/impl-serialize.md
end() should be called on the SerializeSeq, not the Serializer.
My commit message should read typo, not type...
=> Correct a typo on impl-serialize.md

src/SUMMARY.md, src/custom-date-format.md, src/examples.md
Added an example for serializing/deserializing a structure with a custom date/time format using the `chrono` crate.
=> Added example for deserializing a custom date format

_src/deserialize-struct.md
Nothing special, this just irked me.
=> Use ok_or_else() in Deserialize for structs rather than handrolling

_src/field-attrs.md
Document [serde#935](https://github.com/serde-rs/serde/pull/935), and recommend using the combined `skip` attribute instead of `skip_serializing` or `skip_deserializing`.
=> Document the combined `#[serde(skip)]` field attribute

_src/deserialize-map.md, _src/ignored-any.md, _src/stream-array.md, _src/string-or-struct.md, _src/unit-testing.md
Maybe this is not the most important issue for serde, but correct usage
here can help users use PhantomData correctly in general.
We want to use `PhantomData<fn() -> T>` when we are producing, not
owning values of T.
(1) `PhantomData<T>` and (2) `PhantomData<fn() -> T>` have the same variance
implications, but differ in other aspects. (1) makes the type non-Send
if T is non-Send. (2) is always Send + Sync.
PhantomData is supposedly simple to reason about (this is at least the
idea of their construction): the phantom data should mimic what the type
actually does. Deserialization does actually do the equivalent of `fn()
-> T`, we call a function that returns a T value.
(Further evidence is that we have no field that stores any "T", but we
have a method that returns `T` or `Result<T, _>`)
=> Tweak the use of PhantomData

_src/SUMMARY.md, _src/attr-flatten.md, _src/field-attrs.md
This adds docs for the `#[serde(flatten)]` feature from this pull
request: https://github.com/serde-rs/serde/pull/1179
=> Added docs for flattening

_src/field-attrs.md
Noticed a broken link while reading through the docs.
=> Fix link to #[serde(borrow)] example

_src/README.md
I believe I've done this in the past for envy but I can't recall what the appropriate way is for adding new links. I also don't know to to regenerate the html sources. perhaps this repo could using a CONTRIBUTING.md file :)
anyway I recently published a new serde deserializer crate the the same spirit called [envy-store](https://github.com/softprops/envy-store) ( think envy but for aws parameter store) more info [here](https://medium.com/@softprops/manageably-safe-and-secure-4c94a638c957) 
Let me know if there are any other steps and I'll be happy to walk up them
=> add envy store to list of impls

_src/attr-skip-serializing.md
Make it more obvious that the skip_serializing attribute only skips serializing and does not skip deserializing, and make user aware of the `skip` attribute which skips both serializing and deserializing, and `skip_deserializing` attribute which skips deserializing only.
I guess i'm of the opinion that if you only present the attribute `skip_serializing` to the user, the name alone doesn't make it clear that it doesn't skip both (or that there are two more relevant attributes for different behaviors). I realize it's documented in the field attributes section, but if you only look at this example then you may get confused (...as I did).
=> Add note about skip attr on skip_serializing example

_src/README.md
Happy to add back after the documentation has been fleshed out: https://github.com/OneSignal/serde-redis/issues/17.
=> Remove link to serde-redis

_src/field-attrs.md, _src/lifetimes.md, _src/variant-attrs.md
Serde allows borrow to be used transparently on newtype variants,
but this feature wasn't documented.
=> Add documentation for borrow attr on variants

_src/container-attrs.md, _src/field-attrs.md, _src/variant-attrs.md
Added docs for missing Container attributes. These were mostly done by inspecting `serde_derive` source; not by testing the functionality. Hopefully the descriptions are accurate.
Added docs for attributes which can specify different options for `Serialize` and `Deserialize` (fixes #77). I've also grouped these different variants of each attribute together, although I'm not sure how gitbook will render them. Let me know if this styling/grouping could be improved.
=> Add missing attribute documentation

_src/README.md
Disclaimer: I'm the author of `lexpr` and its companion crate `serde-lexpr`.
=> Add a link to `lexpr`, which implements S-expression support

_src/enum-number.md
Example fails to compile without serde_json.
=> Add dependency in enum-number.md

_src/README.md
Bendy, a bencode encoder and decoder, recently added feature-complete
serde support, so I thought it would be good to mention it in the
supported formats list.
=> Mention bencode format support in readme

_src/attr-flatten.md, _src/container-attrs.md, _src/field-attrs.md
There are various bug reports about the interaction of `flatten` and
`deny_unknown_fields`. In the end they cannot really be combined, since
flatten does not consume the fields thus `deny_unknown_fields` will error
on them.
https://github.com/serde-rs/serde/issues/1957
https://github.com/serde-rs/serde/issues/1600
https://github.com/serde-rs/serde/issues/1547
I'm happy to update the wording of the notice to include any suggestions.
=> Add a warning that `flatten` and `deny_unknown_fields` should not be mixed.

_src/README.md
Another crate, [hjson-rust](https://github.com/hjson/hjson-rust) was listed in the past for Hjson but hadn't been made compatible with serde 1.0 and isn't compatible with derive based operations.
This new crate, [deser-hjson](https://github.com/Canop/deser-hjson) is explicitly geared at derive based deserialization.
=> Add the new deser_hjson deserializer for Hjson

_src/derive.md
The `tree` subcommand has since been built directly into Cargo.
=> Remove cargo-tree crate link

_src/no-std.md
Since Rust [release 1.36](https://github.com/rust-lang/rust/blob/master/RELEASES.md#libraries-16), `alloc` is stable.
Closes serde-rs/serde#1943.
=> Remove outdated mention of nightly for alloc feature

_src/README.md
The [`serde_cbor`](https://github.com/pyfisch/cbor) crate [is no longer maintained](https://github.com/pyfisch/cbor/issues/179) and points to [`ciborium`](https://github.com/enarx/ciborium) as worthy successor.
ping https://github.com/enarx/ciborium/issues/20
=> change cbor link to new repo

LICENSE-CC-BY-SA
Rust quiz license link: https://github.com/dtolnay/rust-quiz/blob/master/LICENSE-CC-BY-SA
Closes #139 
@dtolnay do you want a top level README that includes a similar blurb as in the rust-quiz repo? e.g.
```md
The quiz questions, explanations, website, and all other intellectual property in this repository are all licensed under the [Creative Commons Attribution-ShareAlike 4.0 International License](https://github.com/dtolnay/rust-quiz/blob/master/LICENSE-CC-BY-SA).
```
=> Import license from rust-quiz repo

_src/README.md, _src/conventions.md, _src/custom-serialization.md, _src/data-model.md, _src/error-handling.md, _src/ignored-any.md, _src/impl-deserialize.md, _src/impl-deserializer.md, _src/impl-serialize.md, _src/impl-serializer.md, _src/lifetimes.md, _src/unit-testing.md
For a while, docs.serde.rs has just been redirecting to docs.rs.
=> Replace docs.serde.rs links

_src/container-attrs.md
fixes https://github.com/serde-rs/serde/issues/1684
=> Document #[serde(tag)] on struct structs

_src/container-attrs.md
This attribute has flew under the radar of serde documentation since it was introduced by https://github.com/serde-rs/serde/pull/1916. Given how useful it can be to improve untagged enum deserialization error messages and that its introduction has been uncontroversial so far, I think it's a good idea to document it.
=> Document `expecting` container attribute

_src/no-std.md
`alloc` was stabilized on 1.36 and the feature has been stable on serde since Jul/2019 https://github.com/serde-rs/serde/issues/1575
=> doc: alloc is no longer unstable

_src/data-model.md
> As a Serde byte array. This fixes both ~problem~ problems with using string, but now if we serialize an OsString on Unix and deserialize it on Windows we end up with the wrong string.
=> Fix typo in Serde data model page

_src/custom-date-format.md
I came across [this](https://serde.rs/custom-date-format.html) example for using custom date formats when using serde and chrono together. The example uses the function ```Utc.datetime_from_str```, which is deprecated since chrono version 0.4.29.
This PR changes the example to use ```NaiveDateTime::parse_from_str(&self, s: &str, fmt: &str)```, keeping it simple to understand and without using deprecated code.
=> Remove usage of deprecated Utc.datetime_from_str from the custom date format example

_src/impl-serializer.md
This fixes a minor inaccuracy for the item import syntax within the `impl-serializer.md` documentation.
=> docs: tiny fix to `impl-serializer` item import syntax

_src/container-attrs.md
This PR adds documentation for the `variant_identifier` and `field_identifier` attributes on enums. I think this should be alright to make officially part of the public API, since they're [mentioned](https://serde.rs/deserialize-struct.html) in existing documentation, but I'm happy to be wrong about this.
Fixes https://github.com/serde-rs/serde/issues/1238
=> Add documentation for `variant_identifier` and `field_identifier`

_src/enum-representations.md
I was happily writing some code that needs to support no_std and no_alloc only to find out that it's not possible through the compilation simply failing:
```rust
error[E0433]: failed to resolve: could not find `ContentRefDeserializer` in `de`
--> zarlink/src/connection/mod.rs:136:36
|
136 |         #[derive(Debug, Serialize, Deserialize)]
|                                    ^^^^^^^^^^^ could not find `ContentRefDeserializer` in `de`
|
note: found an item that was configured out
--> /home/zeenix/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde-1.0.218/src/private/de.rs:14:35
|
14  |     Content, ContentDeserializer, ContentRefDeserializer, EnumDeserializer,
|                                   ^^^^^^^^^^^^^^^^^^^^^^
note: the item is gated here
--> …
```
=> Document that most enums representations require `std` or `alloc` features

_src/no-std.md
=> JSON now supports no-std

_src/container-attrs.md
I expect a lot of users are like me and just assume their code is fast enough.  It wasn't until I had to do more explicit benchmarks that I found out how slow `untagged` is.  The hope is to make this more discoverable for others along with an easier / less intimidating way of improving performacne via serde-untagged.  See also serde-rs/serde#2101
Similarly, errors can be bad and `expecting` wasn't documented until #153.  This also adds cross-linking to make this attribute more discoverable.
=> Help improve experience with untagged schemas

_src/variant-attrs.md
This patch fixes a broken link. The link is `[enum representation]` but it should be `[enum representations]` as it is defined below with `[enum representations]: enum-representations.md`.
=> Fix a broken link
